add option to sample deterministic actions
joaoamcarvalho/mushroom-rl pull request #2
Opened 2024-08-19 14:34 UTC by nickstr15

2024-08-19 20:56 UTC, jacarvalho requested changes

2024-08-19 20:56 UTC, joaoamcarvalho commented on mushroom_rl/algorithms/actor_critic/deep_actor_critic/sac.py
> +        self.deterministic = True
Just double check this comment. Maybe I missed something.
We want to be able to evaluate both the stochastic and the deterministic policy.
Right now it seems that if you call self.policy.eval(), it will always set the policy to deterministic.

2024-08-20 06:58 UTC, nickstr15 commented on mushroom_rl/algorithms/actor_critic/deep_actor_critic/sac.py
> +        self.deterministic = True
I thought than one would just call .train() and run the evalutaion, but I adapted the code a little bit. See 4c6a3463d628ee55388713923ce5f333850f765d

2024-08-20 08:43 UTC, jacarvalho commented on mushroom_rl/algorithms/actor_critic/deep_actor_critic/sac.py
> +        self.deterministic = True
That's nicer since you can choose which policy to evaluate.

2024-08-20 08:43 UTC, merged